version: '3.9'

services:
  frontend:
    build: ./frontend
    container_name: react_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

  backend:
    build: ./chat-backend
    container_name: node_backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
